"""add rs232 settings table

Revision ID: 4bcfc1b3459f
Revises: '6a5bc204a9d0'
Create Date: autogenerated
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bcfc1b3459f'
down_revision: Union[str, Sequence[str], None] = '6a5bc204a9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "rs232_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("selected_race_id", sa.Integer(), nullable=True),
        sa.Column("port", sa.String(length=255), nullable=True),
        sa.Column("baudrate", sa.Integer(), nullable=False, server_default="9600"),
        sa.Column("timeout_seconds", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["selected_race_id"], ["races.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        """
        INSERT INTO rs232_settings
            (id, selected_race_id, port, baudrate, timeout_seconds, is_enabled, updated_at)
        VALUES
            (1, NULL, NULL, 9600, 1.0, 0, CURRENT_TIMESTAMP)
        """
    )


def downgrade() -> None:
    op.drop_table("rs232_settings")
