"""Add raw scans and scan punches

Revision ID: 7f5e6fcb122e
Revises: 83b60ec3d987
Create Date: 2026-06-26 23:09:27.748249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5e6fcb122e'
down_revision: Union[str, Sequence[str], None] = '83b60ec3d987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('chip_number', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('emit_total_time_raw', sa.String(), nullable=True),
    sa.Column('emit_total_seconds', sa.Integer(), nullable=True),
    sa.Column('scanner_time_raw', sa.String(), nullable=True),
    sa.Column('scanner_time_seconds', sa.Integer(), nullable=True),
    sa.Column('finish_to_scan_time_raw', sa.String(), nullable=True),
    sa.Column('finish_to_scan_seconds', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_scans_id'), 'raw_scans', ['id'], unique=False)
    op.create_table('scan_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_scan_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('emit_code', sa.String(), nullable=True),
    sa.Column('sequence_code', sa.String(), nullable=True),
    sa.Column('split_time_raw', sa.String(), nullable=True),
    sa.Column('split_seconds', sa.Integer(), nullable=True),
    sa.Column('accumulated_time_raw', sa.String(), nullable=True),
    sa.Column('accumulated_seconds', sa.Integer(), nullable=True),
    sa.Column('calculated_time_from_start_seconds', sa.Integer(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('ignore_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['raw_scan_id'], ['raw_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_punches_id'), 'scan_punches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_punches_id'), table_name='scan_punches')
    op.drop_table('scan_punches')
    op.drop_index(op.f('ix_raw_scans_id'), table_name='raw_scans')
    op.drop_table('raw_scans')
    # ### end Alembic commands ###
