"""Add athletes and controls

Revision ID: 83b60ec3d987
Revises: 5fce77a3faf9
Create Date: 2026-06-26 23:07:43.492786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b60ec3d987'
down_revision: Union[str, Sequence[str], None] = '5fce77a3faf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=True),
    sa.Column('chip_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('eqtiming_participant_uid', sa.String(), nullable=True),
    sa.Column('eqtiming_athlete_uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'chip_number', name='uq_athlete_race_chip_number'),
    sa.UniqueConstraint('race_id', 'start_number', name='uq_athlete_race_start_number')
    )
    op.create_index(op.f('ix_athletes_id'), 'athletes', ['id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emit_code', sa.String(), nullable=True),
    sa.Column('is_finish', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'emit_code', name='uq_control_race_emit_code'),
    sa.UniqueConstraint('race_id', 'sort_order', name='uq_control_race_sort_order')
    )
    op.create_index(op.f('ix_controls_id'), 'controls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controls_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_athletes_id'), table_name='athletes')
    op.drop_table('athletes')
    # ### end Alembic commands ###
